### ISSUE TITLE
Error when importing chen

### ISSUE THREAD

**Issue by marchezinixd** [petroniocandido/pyFTS#1]
Jupyter show the following error when trying to import module 'chen'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-15-62b00bc5d8e4> in <module>()
----> 1 from pyFTS import chen

C:\Users\guilherme.marchezini\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyFTS\chen.py in <module>()
      1 import numpy as np
      2 from pyFTS.common import FuzzySet, FLR
----> 3 import fts
      4 
      5 

ImportError: No module named 'fts'

**Comment by petroniocandido** [comment]
a) Which python version are you working with? 
b) Are you working with the last version of pyFTS?
c) Are you working at python shell or with Jupyter notebooks?

Att.

**Comment by marchezinixd** [comment]
A) Python 3.5.2.0
B) Yes, I used the github version 13/01/2017
C) Jupyter notebooks

**Comment by petroniocandido** [comment]
I just sent a patch. Please update your code and try again.
